---
title: "Actigraphy"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(magrittr)
library(tidyverse)
library(lubridate)
library(reshape2)
library(plotly)

acti_files <- readRDS(".\\Data\\actigraphy_header.rds")
actigraphy <- readRDS(".\\Data\\actigraphy_data.rds") 
results <- readRDS(".\\Data\\results.rds") 

actigraphy_static <- actigraphy

off_wrist <- as.data.frame.table(xtabs(~patient_ID + Off_Wrist + Day, data = actigraphy)) %>%
  reshape2::dcast(., formula = patient_ID + Day ~ Off_Wrist, value.var = "Freq") %>%
  rename(Watch_On = `FALSE`, Watch_Off = `TRUE`, Day_number = Day) %>%
  mutate(Percent_Off = 100 * Watch_Off/(Watch_On + Watch_Off),
         Total_Epochs = Watch_On + Watch_Off) %>%
  dplyr::filter(complete.cases(.))

actigraphy %<>% merge(., off_wrist[,c("patient_ID", "Day_number", "Percent_Off", "Total_Epochs")] %>% 
               rename(Day = Day_number), by = c("patient_ID", "Day")) %>%
  dplyr::filter(Percent_Off < (2 / 24), Total_Epochs >= (720 / 2)) %>%
  arrange(patient_ID, DateTime) %>%
  filter(!patient_ID %in% c("Rocko_Jones", "Carolyn_Jones", "Lew_Andrews"))
```

Individual Patients {data-icon="fa-user"}
=====================================

Inputs {.sidebar}
-------------------------------------

```{r, sidepar1}
selectInput("ID", label = "Subject Name:",
            choices = unique(actigraphy_static$patient_ID) %>%
              set_names(gsub("_", " ", .)))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Overview

```{r pg1_overview}
dataset <- reactive({
  dplyr::filter(actigraphy_static, patient_ID == input$ID) %>%
    mutate(Activity_Scale = Activity * (max(Light) / max(Activity)),
           Log_Light = log10(Light)) %>%
    filter(complete.cases(.))
})

renderPlot({
  ggplot(dataset(), mapping = aes(x = Time)) +
    geom_line(aes(y = Light), color = "Orange") +
    geom_line(aes(y = Activity_Scale), color = "Black") +
    facet_grid(Day + DateAbbr ~ .) +
    scale_x_datetime(date_labels = "%I %p", date_minor_breaks = "1 hour") + 
    scale_y_continuous(sec.axis = sec_axis(trans = ~ . * (max(dataset()$Activity) / max(dataset()$Light)),
                                           name = "Activity")) +
    labs(y = "Light", title = gsub("_", " ", input$ID))
})

```

Column {data-width=150}
-----------------------------------------------------------------------

### Days

```{r pg1_days_box}
## Days of measurement
renderValueBox({
  valueBox(length(unique(dataset()$Day)), caption = "Total Days Worn",
           icon = "fa-clock-o")
})
```

### Days Off-Wrist

```{r pg1_days_off_box}
## Days off wrist
renderValueBox({
  valueBox(aggregate(Off_Wrist ~ Day, dataset(), function(ii) sum(ii) > 30) %>%
             select(-Day) %>%
             summarise_each(funs(sum)),
           caption = "Days Off Wrist [1]", icon = "fa-exclamation")
})
```

### Light Adherence

```{r pg1_adherence_box}
## Number of light-adherent bouts
renderValueBox({
  valueBox(filter(results$light_adherence, patient_ID == input$ID) %>%
             select(Bouts) %>% summarise_each(funs(sum)),
           caption = "Light Adherent Bouts [2]",
           icon = "fa-lightbulb-o")
})
```

### Peak Activity

```{r pg1_activity_box}
## Peak activity
renderValueBox({
  valueBox(max(dataset()$Activity), caption = "Peak Activity",
           icon = "fa-bicycle")
})
```

### Peak Light

```{r pg1_light_box}
## Peak light
renderValueBox({
  valueBox(round(max(dataset()$Light)), caption = "Peak Light",
           icon = "fa-sun-o")
})
```

### Average Sleep

```{r pg1_avg_sleep}
## Average Sleep (hours)

avg_sleep <- aggregate(Sleep_Smooth ~ patient_ID + Date + Day, actigraphy_static, table) %>%
  as.data.frame.table(.) %>%
  filter(Var2 == "patient_ID", Freq.Day != 1) %>%
  select(-Var1, -Var2, -Freq.Day) %>%
  set_colnames(c("patient_ID", "Date", "Sleep", "Wake")) %>%
  mutate(Percent_Sleep = 100 * (Sleep/(Sleep + Wake)),
         Date = as.POSIXct(strptime(Date, format = "%F"))) %>%
  merge(., aggregate(Light ~ patient_ID + Date, actigraphy_static, median),
                 by = c("patient_ID", "Date")) %>%
  merge(., aggregate(Activity ~ patient_ID + Date, actigraphy_static, median),
        by = c("patient_ID", "Date")) %>%
  mutate(Hours = (Percent_Sleep / 100) * 24) %>%
  merge(., aggregate(Off_Wrist ~ patient_ID + Date, actigraphy_static, sum),
        by = c("patient_ID", "Date"))

box_avg_sleep <- reactive({
  dplyr::filter(avg_sleep, patient_ID == input$ID, Off_Wrist < 30) %>%
    select(Hours) %>% unlist(.) %>% opelr::numfac(.) %>%
    mean(.) %>% round(., 2)
})

renderValueBox({
  valueBox(box_avg_sleep(), caption = "Avg. Sleep Duration (hrs)",
           icon = "fa-bed")
})
```

### Footnotes {.no-title}

[1]: A day as determined "Off-Wrist" if at least one hour's worth of epochs are detected as off-wrist.    
[2]: A single Light Adherent bout is defined as a period of at least 30 minutes where the median illuminance is greater than or equal to 10k lux/m^2.

Light Adherence {data-icon="fa-sun-o"}
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r, sidebar2}
fns <- c("mean", "median", "max", "min", "sd")
names(fns) <- c("Average", "Median", "Maximum", "Minimum", "Std. Dev.")

selectInput("functions", label = "Function:", choices = fns, selected  = "mean")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Light Exposure

```{r median_light}
light_exposure <- reactive({
  aggregate(Light ~ patient_ID + Hour, actigraphy, get(input$functions))
})

renderPlotly({
  p <- ggplot(light_exposure(), aes(Hour, Light, group = patient_ID,
                                    color = patient_ID)) + 
  geom_line(stat = "identity") +
  scale_x_continuous(breaks = seq(0, 24, 4)) + 
  labs(y = paste0("Light (", input$functions, ")"))
  
  ggplotly(p, tooltip = c("patient_ID", "Light", "Hour")) %>%
    layout(autosize = F, width = 750, height = 750)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B
```{r}
light_adherence <- cbind(aggregate(ABL ~ patient_ID, results$light_adherence, mean),
             aggregate(Bouts ~ patient_ID, results$light_adherence, sum)[2])

renderPlotly({
  p <- ggplot(light_adherence, aes(Bouts, ABL)) +
    geom_point(aes(color = patient_ID), size = 2) +
    geom_smooth(method = "lm") +
    scale_x_continuous(limits = c(0, 12), breaks = seq(0, 12, 4)) +
    labs(y = "Avg. Bout Length (min.)")
  
  ggplotly(p) %>%
    layout(autosize = F, width = 750, height = 750)
  
})
```

Sleep Metrics {data-icon="fa-bed"}
=====================================

Inputs {.sidebar}
-------------------------------------

```{r, sidebar3}
light_activity <- c("Activity", "Light")
selectInput("light_activity", label = "Independent:", choices = light_activity,
            selected  = "Activity")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Sleep Duration as predicted by Light/Activity

```{r}
social_jetlag <- aggregate(Sleep_Smooth ~ patient_ID + Date + Day, actigraphy, table) %>%
  as.data.frame.table(.) %>%
  filter(Var2 == "patient_ID", Freq.Day != 1) %>%
  select(-Var1, -Var2, -Freq.Day) %>%
  set_colnames(c("patient_ID", "Date", "Sleep", "Wake")) %>%
  mutate(Percent_Sleep = 100 * (Sleep/(Sleep + Wake)),
         Date = as.POSIXct(strptime(Date, format = "%F")),
         Weekend = weekdays(Date),
         Weekend = factor(ifelse(Weekend %in% c("Saturday", "Sunday"),
                                 "Weekend", "Weekday")))

compare <- merge(social_jetlag, aggregate(Light ~ patient_ID + Date, actigraphy, median),
                 by = c("patient_ID", "Date")) %>%
  merge(., aggregate(Activity ~ patient_ID + Date, actigraphy, median),
        by = c("patient_ID", "Date")) %>%
  mutate(Hours = (Percent_Sleep / 100) * 24)


renderPlotly({
  p <- ggplot(compare, aes_string(input$light_activity, "Hours")) +
  geom_point(aes(color = patient_ID)) +
  geom_smooth(method = "lm") +
  labs(y = "Sleep (hours)")
  
  ggplotly(p) %>%
    layout(autosize = F, width = 750, height = 750)
})


```


Column {data-width=500}
-----------------------------------------------------------------------

### Average Bed- and Wake-Time

```{r}
ggplot(results$avg_bedtime, aes(DateTime, patient_ID, color = Status)) +
  geom_point() +
  scale_x_datetime(date_breaks = "2 hours",
                   date_labels = "%H:%M") +
  geom_errorbarh(aes(xmax = upper_Date, xmin = lower_Date), height = 0.1) +
  labs(y = "Patient", x = "Time")
```


Activity {data-icon="fa-bicycle"}
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r, sidebar4}
selectInput("radial_ID", label = "Subject Name:",
            choices = unique(actigraphy_static$patient_ID) %>%
              set_names(gsub("_", " ", .)))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Daytime Activity Ratio

```{r}
ggplot(results$DAR, aes(x = patient_ID, y = DAR)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymax = ymax, ymin = ymin), width = 0.25) +
  labs(y = "Daytime Activity Ratio (6:30 AM - 11 PM)")
```

Column {data-width=500}
-----------------------------------------------------------------------


```{r radial_plots}

radial_static <- results$radial_plots

radial <- reactive({
  dplyr::filter(radial_static, patient_ID == input$radial_ID | patient_ID == "mean" )
})


renderPlot({
  ggplot(radial(), aes(Time, Value)) +
  geom_line(data = radial()[radial()$Metric == "Light" & radial()$patient_ID == input$radial_ID, ],
            color = "darkorange", size = 2) +
  geom_line(data = radial()[radial()$Metric == "Activity" & radial()$patient_ID == input$radial_ID, ],
            color = "black", size = 2) +
  geom_line(data = radial()[radial()$Metric == "Light" & radial()$patient_ID == "mean", ],
            color = "darkorange", size = 2, alpha=0.2) +
  geom_line(data = radial()[radial()$Metric == "Activity" & radial()$patient_ID == "mean", ],
            color = "black", size = 2, alpha=0.2) +
  scale_x_datetime(date_labels = "%I %p", date_minor_breaks = "1 hour") +
  # scale_y_continuous(limits = c(0, 10 ^ ceiling(log10(max(radial$Value))))) +
  coord_polar() +
  theme_minimal() +
  labs(y = "", x = "")
}, width = "auto")


```

